# action.yaml
name: 'Telegram File Uploader'
description: 'Upload your GitHub Action files to Telegram via Telethon'
inputs:
  to-who:
    description: 'Send to who'
    required: true
  message:
    description: 'Message'
    required: true
  files:
    description: 'Files (one file per line)'
    required: true
  buttons:
    description: 'Inline buttons in JSON format'
    required: false
outputs:
  status:
    description: 'Command status'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "--to=${{ inputs.to-who }}"
    - "--message=${{ inputs.message }}"
    - "--files=${{ inputs.files }}"
    - "--buttons=${{ inputs.buttons }}"
branding:
  icon: 'upload-cloud'
  color: 'green'
